name: morganowens
favicon: null
layout_spectrum: 0.846497910330072
typography_spectrum: 0.40276650292798877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9188233241438866
  lightness: 0.49386538635008037
  saturation: 0.38105310522951186
  rhythmicContrast: 0.33179042185656726
purpose: []
